name: Deploy to Workshop

on:
  workflow_dispatch:
    inputs:
      changelog:
        type: string
        required: false
        default: "Update to latest Git commit"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project
          
      - name: Remove Non-content
        run: |
          rm -rf $GITHUB_WORKSPACE/project/.git*
          rm -fv $GITHUB_WORKSPACE/project/LICENSE*
          rm -fv $GITHUB_WORKSPACE/project/README*

      - uses: mboxlab/gmod-upload@master
        with:
          id: 3480565494
          changelog: ${{ inputs.changelog }}
        env:
          STEAM_USERNAME: ${{ secrets.WORKSHOP_UPLOADER_USERNAME }}
          STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF }}
