name: Deploy to Workshop

on:
  workflow_dispatch:
    inputs:
      changelog:
        type: string
        required: false
        default: "Update to latest Git commit"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Remove Non-content
        run: |
          rm -rf $GITHUB_WORKSPACE/.git*
          rm -rf $GITHUB_WORKSPACE/.github*
          rm -fv $GITHUB_WORKSPACE/LICENSE*
          rm -fv $GITHUB_WORKSPACE/README*

      - uses: m00nl1ght-dev/steam-workshop-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          path: build
          appId: 4000
          publishedFileId: 3480565494
